# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fce9dd9af636de4a8a167f8ffb4b6f558dffdc02764060533066a9dc8dfb5adc9e9ea9153ff12c4f78977ccc533027a0be5af6efaa3ed3efd6ea46ae242bdf29

test:
  secret_key_base: fc97d1d11b9698eaddf838a53217435725c99d1f97874ba68debb1d647f9ab67aabe1794177e997abbf390f5b8b24508fef70afff61373a947da4429d1d41194

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
